CREATE TABLE LF_BOARD_INFO(
   BOARD_ID INT NOT NULL auto_increment primary key,
   BOARD_NAME VARCHAR2(255),
   ACCESS_LEVEL INT(11),
)

CREATE TABLE LF_BOARD(
   BOARD_ID INT,
   ARTICLE_ID INT NOT NULL auto_increment primary key,
   ARTICLE_NAME VARCHAR2(255),
   CONTENTS BLOB,
   READ_COUNT,
   LIKE_COUNT,
   NOTICE_YN,
   UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
   INDEX ARTICLE_ID_NAME (ARTICLE_ID, ARTICLE_NAME)
)

CREATE TABLE LF_COMMENTS(
   COMMENT_ID INT NOT NULL auto_increment primary key,
   PARENT_ID INT(11),
   ARTICLE_ID INT(11),
   USER_IDX INT,
   COMMENT BLOB,
   IS_DELETE VARCHAR2(1) DEFAULT 'N',
   UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE LF_USER(
   USER_IDX INT NOT NULL auto_increment PRIMARY KEY,
   USER_ID VARCHAR2(255),
   USER_PASSWORD PASSWORD,
   USER_NICKNAME VARCHAR2(255),
   USER_NAME VARCHAR2(50),
   USER_PHONE VARCHAR2(20),
   USER_STATE VARCHAR2(50),
   USER_TYPE VARCHAR2(100),
   USER_LEVEL INT,
   USER_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
   INDEX USER_ID_NICKNAME_INDEX (USER_IDX, USER_ID, USER_NICKNAME)
)

CREATE TABLE LF_USER_GRADE(
   GRADE_CODE INT NOT NULL auto_increment primary key,
   GRADE_NAME VARCHAR2(255),
   GRADE_DESC VARCHAR2(255)
)